function(target_import_FatFs target_name visibility)
	set(lib_name "FatFs")
	target_include_directories(${target_name} ${visibility} ${libs_path}/${lib_name}/include/)
	target_auto_link_lib(${target_name} ${lib_name} ${libs_path}/${lib_name}/lib/)
	install_dll_dir(${libs_path}/${lib_name}/bin/)
endfunction()
