include(target_import_base)
include(target_import_qt)
include(target_import_qxlsx)

function(target_import_widget target_name visibility)
	set(lib_name "widget")
    target_include_directories(${target_name} ${visibility} $ENV{cpp_lib_build_scripts_path}/${platform}/.libs/${lib_name}/include/)
    target_auto_link_lib(${target_name} ${lib_name} $ENV{cpp_lib_build_scripts_path}/${platform}/.libs/${lib_name}/lib/)

	target_import_base(${target_name} ${visibility})
	target_import_qt_widgets(${target_name} PUBLIC)
	target_import_qt_opengl(${target_name} PUBLIC)
	target_import_qwt(${target_name} PUBLIC)
	target_import_qxlsx(${target_name} PUBLIC)
endfunction()
