function(target_import_npcap target_name visibility)
	set(lib_name npcap)
    target_include_directories(${target_name} ${visibility} $ENV{cpp_lib_build_scripts_path}/${platform}/.libs/${lib_name}/include/)
	target_auto_link_lib(${target_name} wpcap $ENV{cpp_lib_build_scripts_path}/${platform}/.libs/${lib_name}/lib/)
endfunction()
