function(target_import_npcap target_name visibility)
	set(lib_name npcap)
    target_include_directories(${target_name} ${visibility} "${libs_path}/${lib_name}/include/")
	target_auto_link_lib(${target_name} wpcap ${libs_path}/${lib_name}/lib/)
endfunction()
