function(target_import_base target_name visibility)
    target_include_directories(${target_name} ${visibility} ${libs_path}/base/include/)
    target_auto_link_lib(${target_name} base ${libs_path}/base/lib/)
    install_dll_dir(${libs_path}/base/bin/)
endfunction()
