include(target_import_base)
include(target_import_bsp_interface)
include(target_import_stm32f103zet6_hal)
include(target_import_task)

function(target_import_stm32f103zet6_serial target_name visibility)
	set(lib_name "stm32f103zet6-serial")
	target_include_directories(${target_name} ${visibility} $ENV{cpp_lib_build_scripts_path}/${platform}/.libs/${lib_name}/include/)
	target_auto_link_lib(${target_name} ${lib_name} $ENV{cpp_lib_build_scripts_path}/${platform}/.libs/${lib_name}/lib/)

	target_import_base(${target_name} ${visibility})
	target_import_bsp_interface(${target_name} ${visibility})
	target_import_task(${target_name} ${visibility})
	target_import_stm32f103zet6_hal(${target_name} PRIVATE)
endfunction()
