function(target_import_task target_name visibility)
    target_include_directories(${target_name} ${visibility} ${libs_path}/task/include/)
    target_auto_link_lib(${target_name} task ${libs_path}/task/lib/)
    install_dll_dir(${libs_path}/task/bin/)
endfunction()
